[package]
name = "sadra_fusion_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
itertools = "0.13.0"
ndarray = {version = "0.16.0", features= ["rayon" , "approx" , "docs"]}
rand = "0.8.5"
rand_distr = "0.4.3"
